# All of the files in "src" are generated by this python script.

import json
import re

NUMERIC_PATTERN = r"[IUF]\d+"
JMPTABLE_ADDR = 0x037FC000

CODEGEN_HEADER = """// This file was programmatically generated. These symbols may resolve to the incorrect location if firmware changes.\n"""


def holyc_to_zig(hc_type: str) -> str:
    if hc_type == "U0":
        return "void"
    elif bool(re.fullmatch(NUMERIC_PATTERN, hc_type)):
        return hc_type.lower()
    elif "*" in hc_type:
        return "[*c]" + holyc_to_zig(hc_type.replace("*", "")).strip()
    elif "VaList" == hc_type:
        return "..."
    elif "Bool" == hc_type:
        return "bool"
    else:
        # struct type
        return f"types.{hc_type}"


data: dict = {}

with open("data/jumptable.json") as f:
    data = json.load(f)

with open("./src/types.zig", "w") as f:
    f.write(
        "//! Type definitions for structs defined in the VEX API\n" + CODEGEN_HEADER
    )
    f.writelines(
        [
            f"pub const {x} = opaque {{}};\n"
            for x in [
                "V5_DeviceT",
                "V5_DeviceOpticalRaw",
                "V5_DeviceAiVisionColor",
                "V5_DeviceAiVisionCode",
                "V5_DeviceAiVisionObject",
                "V5_DeviceArmTipPosition",
                "V5_DeviceMagnetDuration",
                "V5_DevicePneumaticCtrl",
                "FIL",
                "FRESULT",
                "v5_image",
                "VaList",
                "V5_TouchStatus",
                "V5_DeviceOpticalGesture",
                "V5_DeviceOpticalRgb",
                "V5_DeviceGpsRaw",
                "V5_DeviceGpsAttitude",
                "V5_DeviceGpsQuaternion",
                "V5_DeviceImuRaw",
                "V5_DeviceImuAttitude",
                "V5_DeviceImuQuaternion",
                "V5VisionWifiMode",
                "V5_DeviceVisionRgb",
                "V5VisionWBMode",
                "V5_DeviceVisionSignature",
                "V5_DeviceVisionObject",
                "V5VisionMode",
                "V5_DeviceLedColor",
                "V5_DeviceBumperState",
                "V5_AdiPortConfiguration",
                "V5_DeviceMotorPid",
                "V5MotorGearset",
                "V5MotorBrakeMode",
                "V5MotorEncoderUnits",
                "V5MotorControlMode",
                "V5_ControllerStatus",
                "V5_ControllerId",
                "V5_DeviceType",
                "date",
                "time",
                "V5_ControllerIndex",
            ]
        ]
    )

files = [open(f"./src/{x}.zig", "w") for x in data["groups"]]  # noqa: SIM115
linker_script = open("addrs.ld", "w")  # noqa: SIM115

i = 0
for file in files:
    file.write(
        f"//! This file was derived from the '{data['groups'][i]}' symbol group \n"
        + CODEGEN_HEADER
        + 'const types = @import("./types.zig");\n'
    )
    i += 1

for addr, metadata in data["entries"].items():
    files[metadata["group"]].write(
        # f'/// Symbol "{metadata["name"]}". Resolves to offset {addr}. {hex(int(addr, 16) + JMPTABLE_ADDR)} in memory. \n'
        f"pub extern const {metadata['name']}: *const fn({', '.join([f'{x["name"]}: {holyc_to_zig(x["type"])}' if (x['type']) != 'VaList' else '...' for x in metadata['params']])}) callconv(.c) {holyc_to_zig(metadata['returnType'])};\n"
    )
    linker_script.write(f"{metadata['name']} = {hex(JMPTABLE_ADDR + int(addr, 16))};\n")

for file in files:
    file.close()

linker_script.close()

import os
import urllib.parse


def grep_folder(search_string, folder_path) -> bool:
    for root, _, files in os.walk(folder_path):
        for file in files:
            file_path = os.path.join(root, file)

            try:
                with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                    for line_num, line in enumerate(f, 1):
                        if search_string in line:
                            return True
            except (PermissionError, IsADirectoryError):
                continue
    return False


def offset_lookup(lookup: str) -> int:
    txt: str
    with open("./data/offsets.txt") as f:
        txt = f.read()
    for line in txt.splitlines():
        if line.startswith("#") or line.strip() == "":
            continue
        [symbol, offset] = line.split()
        if symbol == lookup:
            return int(offset, 16)
    return -1


def generate_docs(addr, entry):
    is_private = grep_folder(entry["name"], "./data/private_api")
    found_offset = offset_lookup(entry["name"])
    if found_offset == -1:
        print(f"function not defined in txt: {entry['name']}")
    has_contradiction = found_offset != int(addr, 16) and found_offset != -1
    if has_contradiction:
        print(
            f"Datasources contradict on {entry['name']}! json={addr}, txt={hex(found_offset)}\n\tImplicitly trusting json."
        )
    docs = f"""# {entry["name"]}
        Group: "{group}"
        Offset: {addr} ({hex(int(addr, 16) + JMPTABLE_ADDR)})
        Private: {is_private}
        [Find Usages](https://github.com/search?q={urllib.parse.quote(f"org:purduesigbots OR org:vexide OR repo:cetio/VEXAPI OR repo:sy1vi3/sylib OR user:skzidev {entry['name']}(")}&type=code)"""
    return "\n".join([f"/// {line.strip()}\n///" for line in docs.splitlines()]) + "\n"


with open("./src/root.zig", "w") as f:
    f.write(
        "///! This file re-exports all of the symbols from groups.\n" + CODEGEN_HEADER
    )
    f.writelines(
        [f'const {group} = @import("./{group}.zig");\n' for group in data["groups"]]
    )
    for index, group in enumerate(data["groups"]):
        f.write(f"\n// Group '{group}'\n\n")
        f.writelines(
            [
                generate_docs(addr, x)
                + f"pub const {x['name']} = {group}.{x['name']};\n"
                for addr, x in data["entries"].items()
                if x["group"] == index
            ]
        )
