const types = @import("types.zig");
pub extern const vexDeviceOpticalHueGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.double;
pub extern const vexDeviceOpticalSatGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.double;
pub extern const vexDeviceOpticalBrightnessGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.double;
pub extern const vexDeviceOpticalProximityGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceOpticalRgbGet: *const fn(device: types.V5_DeviceT,data: [*c]types.V5_DeviceOpticalRgb) callconv(.c) void;
pub extern const vexDeviceOpticalLedPwmSet: *const fn(device: types.V5_DeviceT,value: i32) callconv(.c) void;
pub extern const vexDeviceOpticalLedPwmGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceOpticalStatusGet: *const fn(device: types.V5_DeviceT) callconv(.c) u32;
pub extern const vexDeviceOpticalRawGet: *const fn(device: types.V5_DeviceT,data: [*c]types.V5_DeviceOpticalRaw) callconv(.c) void;
pub extern const vexDeviceOpticalModeSet: *const fn(device: types.V5_DeviceT,mode: u32) callconv(.c) void;
pub extern const vexDeviceOpticalModeGet: *const fn(device: types.V5_DeviceT) callconv(.c) u32;
pub extern const vexDeviceOpticalGestureGet: *const fn(_: types.V5_DeviceT,pData: [*c]types.V5_DeviceOpticalGesture) callconv(.c) u32;
pub extern const vexDeviceOpticalGestureEnable: *const fn(_: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceOpticalGestureDisable: *const fn(_: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceOpticalProximityThreshold: *const fn(device: types.V5_DeviceT,value: i32) callconv(.c) i32;
pub extern const vexDeviceOpticalIntegrationTimeSet: *const fn(device: types.V5_DeviceT,timeMs: types.double) callconv(.c) void;
pub extern const vexDeviceOpticalIntegrationTimeGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.double;
