//! This file was derived from the 'arm' symbol group 
// This file was programmatically generated. These symbols may resolve to the incorrect location if firmware changes.
const types = @import("./types.zig");
pub extern const vexDeviceArmMoveTipCommandLinearAdv: *const fn(device: types.V5_DeviceT, position: [*c]types.V5_DeviceArmTipPosition, j6_rotation: f64, j6_velocity: u16, relative: bool) callconv(.c) void;
pub extern const vexDeviceArmMoveTipCommandJointAdv: *const fn(device: types.V5_DeviceT, position: [*c]types.V5_DeviceArmTipPosition, j6_rotation: f64, j6_velocity: u16, relative: bool) callconv(.c) void;
pub extern const vexDeviceArmTipPositionGetAdv: *const fn(device: types.V5_DeviceT, position: [*c]types.V5_DeviceArmTipPosition) callconv(.c) void;
pub extern const vexDeviceArmPoseSet: *const fn(device: types.V5_DeviceT, pose: u8, velocity: u16) callconv(.c) void;
pub extern const vexDeviceArmMoveTipCommandLinear: *const fn(device: types.V5_DeviceT, x: i32, y: i32, z: i32, pose: u8, velocity: u16, rotation: f64, rot_velocity: u16, relative: bool) callconv(.c) void;
pub extern const vexDeviceArmMoveTipCommandJoint: *const fn(device: types.V5_DeviceT, x: i32, y: i32, z: i32, pose: u8, velocity: u16, rotation: f64, rot_velocity: u16, relative: bool) callconv(.c) void;
pub extern const vexDeviceArmMoveJointsCommand: *const fn(device: types.V5_DeviceT, positions: [*c]f64, velocities: [*c]u16, j6_rotation: f64, j6_velocity: u16, j7_volts: f64, j7_timeout: u16, j7_i_limit: u16, relative: bool) callconv(.c) void;
pub extern const vexDeviceArmSpinJoints: *const fn(device: types.V5_DeviceT, velocities: [*c]f64) callconv(.c) void;
pub extern const vexDeviceArmSetJointPositions: *const fn(device: types.V5_DeviceT, new_positions: [*c]f64) callconv(.c) void;
pub extern const vexDeviceArmPickUpCommand: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmDropCommand: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmMoveVoltsCommand: *const fn(device: types.V5_DeviceT, voltages: [*c]f64) callconv(.c) void;
pub extern const vexDeviceArmFullStop: *const fn(device: types.V5_DeviceT, brakeMode: u8) callconv(.c) void;
pub extern const vexDeviceArmEnableProfiler: *const fn(device: types.V5_DeviceT, enable: u8) callconv(.c) void;
pub extern const vexDeviceArmProfilerVelocitySet: *const fn(device: types.V5_DeviceT, linear_velocity: u16, joint_velocity: u16) callconv(.c) void;
pub extern const vexDeviceArmSaveZeroValues: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmForceZeroCommand: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmClearZeroValues: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmBootload: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmTipPositionGet: *const fn(device: types.V5_DeviceT, x: [*c]i32, y: [*c]i32, z: [*c]i32) callconv(.c) void;
pub extern const vexDeviceArmJointInfoGet: *const fn(device: types.V5_DeviceT, positions: [*c]f64, velocities: [*c]f64, currents: [*c]i32) callconv(.c) void;
pub extern const vexDeviceArmJ6PositionGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceArmBatteryGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceArmServoFlagsGet: *const fn(device: types.V5_DeviceT, servoID: u32) callconv(.c) i32;
pub extern const vexDeviceArmStatusGet: *const fn(device: types.V5_DeviceT) callconv(.c) u32;
pub extern const vexDeviceArmDebugGet: *const fn(device: types.V5_DeviceT, id: i32) callconv(.c) u32;
pub extern const vexDeviceArmJointErrorsGet: *const fn(device: types.V5_DeviceT, errors: [*c]u8) callconv(.c) void;
pub extern const vexDeviceArmJ6PositionSet: *const fn(device: types.V5_DeviceT, position: i16) callconv(.c) void;
pub extern const vexDeviceArmStopJointsCommand: *const fn(device: types.V5_DeviceT, brakeModes: [*c]i16) callconv(.c) void;
pub extern const vexDeviceArmReboot: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceArmTipOffsetSet: *const fn(device: types.V5_DeviceT, x: i32, y: i32, z: i32) callconv(.c) void;
