const types = @import("types.zig");
pub extern const vexDisplayForegroundColor: *const fn(col: u32) callconv(.c) void;
pub extern const vexDisplayBackgroundColor: *const fn(col: u32) callconv(.c) void;
pub extern const vexDisplayForegroundColorGet: *const fn() callconv(.c) u32;
pub extern const vexDisplayBackgroundColorGet: *const fn() callconv(.c) u32;
pub extern const vexDisplayErase: *const fn() callconv(.c) void;
pub extern const vexDisplayScroll: *const fn(nStartLine: i32,nLines: i32) callconv(.c) void;
pub extern const vexDisplayScrollRect: *const fn(x1: i32,y1: i32,x2: i32,y2: i32,nLines: i32) callconv(.c) void;
pub extern const vexDisplayCopyRect: *const fn(x1: i32,y1: i32,x2: i32,y2: i32,pSrc: [*c]u32,srcStride: i32) callconv(.c) void;
pub extern const vexDisplayPixelSet: *const fn(x: u32,y: u32) callconv(.c) void;
pub extern const vexDisplayPixelClear: *const fn(x: u32,y: u32) callconv(.c) void;
pub extern const vexDisplayLineDraw: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayLineClear: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayRectDraw: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayRectClear: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayRectFill: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayCircleDraw: *const fn(xc: i32,yc: i32,radius: i32) callconv(.c) void;
pub extern const vexDisplayCircleClear: *const fn(xc: i32,yc: i32,radius: i32) callconv(.c) void;
pub extern const vexDisplayCircleFill: *const fn(xc: i32,yc: i32,radius: i32) callconv(.c) void;
pub extern const vexDisplayPrintf: *const fn(xpos: i32,ypos: i32,bOpaque: u32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayString: *const fn(nLineNumber: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayBigString: *const fn(nLineNumber: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayBigStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplaySmallStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayCenteredString: *const fn(nLineNumber: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayBigCenteredString: *const fn(nLineNumber: i32,format: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayVPrintf: *const fn(xpos: i32,ypos: i32,bOpaque: u32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVString: *const fn(nLineNumber: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVBigString: *const fn(nLineNumber: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVBigStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVSmallStringAt: *const fn(xpos: i32,ypos: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVCenteredString: *const fn(nLineNumber: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayVBigCenteredString: *const fn(nLineNumber: i32,format: [*:0]const u8,args: types.int) callconv(.c) void;
pub extern const vexDisplayTextSize: *const fn(n: u32,d: u32) callconv(.c) void;
pub extern const vexDisplayFontNamedSet: *const fn(pFontName: [*:0]const u8) callconv(.c) void;
pub extern const vexDisplayStringWidthGet: *const fn(pString: [*:0]const u8) callconv(.c) i32;
pub extern const vexDisplayStringHeightGet: *const fn(pString: [*:0]const u8) callconv(.c) i32;
pub extern const vexDisplayRender: *const fn(bVsyncWait: types.int,bRunScheduler: types.int) callconv(.c) types.int;
pub extern const vexDisplayDoubleBufferDisable: *const fn() callconv(.c) void;
pub extern const vexDisplayClipRegionSet: *const fn(x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
pub extern const vexDisplayClipRegionClear: *const fn() callconv(.c) void;
pub extern const vexDisplayThemeIdGet: *const fn() callconv(.c) types.int;
pub extern const vexDisplayRotateFlagGet: *const fn() callconv(.c) types.int;
pub extern const vexDisplayClipRegionSetWithIndex: *const fn(index: i32,x1: i32,y1: i32,x2: i32,y2: i32) callconv(.c) void;
