//! This file was derived from the 'display' symbol group 
// This file was programmatically generated. These symbols may resolve to the incorrect location if firmware changes.
const types = @import("./types.zig");
pub extern const vexDisplayForegroundColor: *const fn(col: u32) callconv(.c) void;
pub extern const vexDisplayBackgroundColor: *const fn(col: u32) callconv(.c) void;
pub extern const vexDisplayErase: *const fn() callconv(.c) void;
pub extern const vexDisplayScroll: *const fn(nStartLine: i32, nLines: i32) callconv(.c) void;
pub extern const vexDisplayScrollRect: *const fn(x1: i32, y1: i32, x2: i32, y2: i32, nLines: i32) callconv(.c) void;
pub extern const vexDisplayCopyRect: *const fn(x1: i32, y1: i32, x2: i32, y2: i32, pSrc: [*c]u32, srcStride: i32) callconv(.c) void;
pub extern const vexDisplayPixelSet: *const fn(x: u32, y: u32) callconv(.c) void;
pub extern const vexDisplayPixelClear: *const fn(x: u32, y: u32) callconv(.c) void;
pub extern const vexDisplayLineDraw: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayLineClear: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayRectDraw: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayRectClear: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayRectFill: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayCircleDraw: *const fn(xc: i32, yc: i32, radius: i32) callconv(.c) void;
pub extern const vexDisplayCircleClear: *const fn(xc: i32, yc: i32, radius: i32) callconv(.c) void;
pub extern const vexDisplayCircleFill: *const fn(xc: i32, yc: i32, radius: i32) callconv(.c) void;
pub extern const vexDisplayVPrintf: *const fn(xpos: i32, ypos: i32, bOpaque: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVString: *const fn(nLineNumber: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVStringAt: *const fn(xpos: i32, ypos: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVBigString: *const fn(nLineNumber: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVBigStringAt: *const fn(xpos: i32, ypos: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVCenteredString: *const fn(nLineNumber: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayVBigCenteredString: *const fn(nLineNumber: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayTextSize: *const fn(n: u32, d: u32) callconv(.c) void;
pub extern const vexDisplayVSmallStringAt: *const fn(xpos: i32, ypos: i32, format: [*c]i8, ...) callconv(.c) void;
pub extern const vexDisplayFontNamedSet: *const fn(pFontName: [*c]i8) callconv(.c) void;
pub extern const vexDisplayForegroundColorGet: *const fn() callconv(.c) u32;
pub extern const vexDisplayBackgroundColorGet: *const fn() callconv(.c) u32;
pub extern const vexDisplayStringWidthGet: *const fn(pString: [*c]i8) callconv(.c) i32;
pub extern const vexDisplayStringHeightGet: *const fn(pString: [*c]i8) callconv(.c) i32;
pub extern const vexDisplayClipRegionSet: *const fn(x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexDisplayRender: *const fn(bVsyncWait: bool, bRunScheduler: bool) callconv(.c) void;
pub extern const vexDisplayDoubleBufferDisable: *const fn() callconv(.c) void;
pub extern const vexDisplayClipRegionSetWithIndex: *const fn(index: i32, x1: i32, y1: i32, x2: i32, y2: i32) callconv(.c) void;
pub extern const vexImageBmpRead: *const fn(ibuf: [*c]u8, oBuf: [*c]types.v5_image, maxw: u32, maxh: u32) callconv(.c) u32;
pub extern const vexImagePngRead: *const fn(ibuf: [*c]u8, oBuf: [*c]types.v5_image, maxw: u32, maxh: u32, ibuflen: u32) callconv(.c) u32;
