//! This file was derived from the 'motor' symbol group 
// This file was programmatically generated. These symbols may resolve to the incorrect location if firmware changes.
const types = @import("./types.zig");
pub extern const vexDeviceMotorVelocitySet: *const fn(device: types.V5_DeviceT, velocity: i32) callconv(.c) void;
pub extern const vexDeviceMotorVelocityGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorActualVelocityGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorDirectionGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorModeSet: *const fn(device: types.V5_DeviceT, mode: types.V5MotorControlMode) callconv(.c) void;
pub extern const vexDeviceMotorModeGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.V5MotorControlMode;
pub extern const vexDeviceMotorPwmSet: *const fn(device: types.V5_DeviceT, pwm: i32) callconv(.c) void;
pub extern const vexDeviceMotorPwmGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorCurrentLimitSet: *const fn(device: types.V5_DeviceT, limit: i32) callconv(.c) void;
pub extern const vexDeviceMotorCurrentLimitGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorCurrentGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorPowerGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorTorqueGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorEfficiencyGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorTemperatureGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorOverTempFlagGet: *const fn(device: types.V5_DeviceT) callconv(.c) bool;
pub extern const vexDeviceMotorCurrentLimitFlagGet: *const fn(device: types.V5_DeviceT) callconv(.c) bool;
pub extern const vexDeviceMotorZeroVelocityFlagGet: *const fn(device: types.V5_DeviceT) callconv(.c) bool;
pub extern const vexDeviceMotorZeroPositionFlagGet: *const fn(device: types.V5_DeviceT) callconv(.c) bool;
pub extern const vexDeviceMotorReverseFlagSet: *const fn(device: types.V5_DeviceT, reverse: bool) callconv(.c) void;
pub extern const vexDeviceMotorReverseFlagGet: *const fn(device: types.V5_DeviceT) callconv(.c) bool;
pub extern const vexDeviceMotorEncoderUnitsSet: *const fn(device: types.V5_DeviceT, units: types.V5MotorEncoderUnits) callconv(.c) void;
pub extern const vexDeviceMotorEncoderUnitsGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.V5MotorEncoderUnits;
pub extern const vexDeviceMotorBrakeModeSet: *const fn(device: types.V5_DeviceT, mode: types.V5MotorBrakeMode) callconv(.c) void;
pub extern const vexDeviceMotorBrakeModeGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.V5MotorBrakeMode;
pub extern const vexDeviceMotorPositionSet: *const fn(device: types.V5_DeviceT, position: f64) callconv(.c) void;
pub extern const vexDeviceMotorPositionGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorPositionRawGet: *const fn(device: types.V5_DeviceT, timestamp: [*c]u32) callconv(.c) i32;
pub extern const vexDeviceMotorPositionReset: *const fn(device: types.V5_DeviceT) callconv(.c) void;
pub extern const vexDeviceMotorTargetGet: *const fn(device: types.V5_DeviceT) callconv(.c) f64;
pub extern const vexDeviceMotorServoTargetSet: *const fn(device: types.V5_DeviceT, position: f64) callconv(.c) void;
pub extern const vexDeviceMotorAbsoluteTargetSet: *const fn(device: types.V5_DeviceT, position: f64, veloctiy: i32) callconv(.c) void;
pub extern const vexDeviceMotorRelativeTargetSet: *const fn(device: types.V5_DeviceT, position: f64, velocity: i32) callconv(.c) void;
pub extern const vexDeviceMotorFaultsGet: *const fn(device: types.V5_DeviceT) callconv(.c) u32;
pub extern const vexDeviceMotorFlagsGet: *const fn(device: types.V5_DeviceT) callconv(.c) u32;
pub extern const vexDeviceMotorVoltageSet: *const fn(device: types.V5_DeviceT, voltage: i32) callconv(.c) void;
pub extern const vexDeviceMotorVoltageGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorGearingSet: *const fn(device: types.V5_DeviceT, gearset: types.V5MotorGearset) callconv(.c) void;
pub extern const vexDeviceMotorGearingGet: *const fn(device: types.V5_DeviceT) callconv(.c) types.V5MotorGearset;
pub extern const vexDeviceMotorVoltageLimitSet: *const fn(device: types.V5_DeviceT, limit: i32) callconv(.c) void;
pub extern const vexDeviceMotorVoltageLimitGet: *const fn(device: types.V5_DeviceT) callconv(.c) i32;
pub extern const vexDeviceMotorVelocityUpdate: *const fn(device: types.V5_DeviceT, velocity: i32) callconv(.c) void;
pub extern const vexDeviceMotorPositionPidSet: *const fn(device: types.V5_DeviceT, pid: [*c]types.V5_DeviceMotorPid) callconv(.c) void;
pub extern const vexDeviceMotorVelocityPidSet: *const fn(device: types.V5_DeviceT, pid: [*c]types.V5_DeviceMotorPid) callconv(.c) void;
pub extern const vexDeviceMotorExternalProfileSet: *const fn(device: types.V5_DeviceT, position: f64, velocity: i32) callconv(.c) void;
