//! This file was derived from the 'system' symbol group 
// This file was programmatically generated. These symbols may resolve to the incorrect location if firmware changes.
const types = @import("./types.zig");
pub extern const vexScratchMemoryPtr: *const fn(ptr: [*c]u8) callconv(.c) i32;
pub extern const vex_vprintf: *const fn(format: [*c]i8, ...) callconv(.c) i32;
pub extern const vex_vsprintf: *const fn(out: [*c]i8, format: [*c]i8, ...) callconv(.c) i32;
pub extern const vex_vsnprintf: *const fn(out: [*c]i8, max_len: u32, format: [*c]i8, ...) callconv(.c) i32;
pub extern const vexSystemVersion: *const fn() callconv(.c) u32;
pub extern const vexStdlibVersion: *const fn() callconv(.c) u32;
pub extern const vexSystemTimeGet: *const fn() callconv(.c) u32;
pub extern const vexGettime: *const fn() callconv(.c) types.time;
pub extern const vexGetdate: *const fn() callconv(.c) types.date;
pub extern const vexSystemMemoryDump: *const fn() callconv(.c) void;
pub extern const vexSystemDigitalIO: *const fn(pin: u32, value: u32) callconv(.c) void;
pub extern const vexSystemStartupOptions: *const fn() callconv(.c) u32;
pub extern const vexSystemExitRequest: *const fn() callconv(.c) void;
pub extern const vexSystemHighResTimeGet: *const fn() callconv(.c) u64;
pub extern const vexSystemPowerupTimeGet: *const fn() callconv(.c) u64;
pub extern const vexSystemLinkAddrGet: *const fn() callconv(.c) u32;
pub extern const vexSystemUsbStatus: *const fn() callconv(.c) u32;
pub extern const vexSystemTimerStop: *const fn() callconv(.c) void;
pub extern const vexSystemTimerClearInterrupt: *const fn() callconv(.c) void;
pub extern const vexSystemTimerReinitForRtos: *const fn(priority: u32, handler: [*c]u8) callconv(.c) i32;
pub extern const vexSystemApplicationIRQHandler: *const fn(ulICCIAR: u32) callconv(.c) void;
pub extern const vexSystemWatchdogReinitRtos: *const fn() callconv(.c) i32;
pub extern const vexSystemWatchdogGet: *const fn() callconv(.c) u32;
pub extern const vexSystemBoot: *const fn() callconv(.c) void;
pub extern const vexSystemUndefinedException: *const fn() callconv(.c) void;
pub extern const vexSystemFIQInterrupt: *const fn() callconv(.c) void;
pub extern const vexSystemIRQInterrupt: *const fn() callconv(.c) void;
pub extern const vexSystemSWInterrupt: *const fn() callconv(.c) void;
pub extern const vexSystemDataAbortInterrupt: *const fn() callconv(.c) void;
pub extern const vexSystemPrefetchAbortInterrupt: *const fn() callconv(.c) void;
pub extern const vexScratchMemoryLock: *const fn() callconv(.c) bool;
pub extern const vexScratchMemoryUnlock: *const fn() callconv(.c) void;
