const types = @import("types.zig");
pub extern const vexBackgroundProcessing: *const fn() callconv(.c) void;
pub extern const vexTaskAdd: *const fn(callback: [*c]fn() callconv(.c) i32,interval: i32,label: [*:0]const u8) callconv(.c) u32;
pub extern const vexTaskAddSimple: *const fn(callback: [*c]void,interval: types.int,label: [*c]types.char) callconv(.c) void;
pub extern const vexTaskAddSimpleWithPriority: *const fn(callback: [*c]void,interval: types.int,label: [*c]types.char,priority: u16) callconv(.c) void;
pub extern const vexTaskAddWithArg: *const fn(callback: [*c]fn() callconv(.c) i32,interval: i32,arg: [*c]void,label: [*:0]const u8) callconv(.c) u32;
pub extern const vexTaskAddWithPriority: *const fn(callback: [*c]fn() callconv(.c) i32,interval: i32,label: [*:0]const u8,priority: i32) callconv(.c) u32;
pub extern const vexTaskAddWithPriorityWithArg: *const fn(callback: [*c]fn() callconv(.c) i32,interval: i32,arg: [*c]void,label: [*:0]const u8,priority: i32) callconv(.c) u32;
pub extern const vexTaskCheckTimeslice: *const fn() callconv(.c) void;
pub extern const vexTaskFree: *const fn(_: [*c]void) callconv(.c) u32;
pub extern const vexTaskGet: *const fn(_: [*c]void) callconv(.c) u8;
pub extern const vexTaskGetCallbackAndId: *const fn(index: u32,callback_id: [*c]i32) callconv(.c) [*c]void;
pub extern const vexTaskGetIndex: *const fn() callconv(.c) u32;
pub extern const vexTaskGetTaskIndex: *const fn(task: [*c]void) callconv(.c) u32;
pub extern const vexTaskHardwareConcurrency: *const fn() callconv(.c) u32;
pub extern const vexTaskPriorityGet: *const fn(callback: [*c]void) callconv(.c) i32;
pub extern const vexTaskPriorityGetWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) i32;
pub extern const vexTaskPrioritySet: *const fn(callback: [*c]void,_: i32) callconv(.c) void;
pub extern const vexTaskPrioritySetWithId: *const fn(callback: [*c]void,ID: i32,priority: u32) callconv(.c) void;
pub extern const vexTaskRemoveAllUser: *const fn(main: [*c]i32) callconv(.c) void;
pub extern const vexTaskResumeWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) void;
pub extern const vexTaskRegister: *const fn(name: [*c]types.char) callconv(.c) void;
pub extern const vexTaskRegisterPersistant: *const fn(name: [*c]types.char,p: types.int) callconv(.c) void;
pub extern const vexTasksDump: *const fn() callconv(.c) void;
pub extern const vexTaskSleep: *const fn(time: u32) callconv(.c) void;
pub extern const vexTasksRun: *const fn() callconv(.c) u32;
pub extern const vexTaskStackDefaultSizeGet: *const fn() callconv(.c) u32;
pub extern const vexTaskStackSizeGet: *const fn() callconv(.c) types.int;
pub extern const vexTaskStackTopGet: *const fn(_: u32) callconv(.c) [*c]void;
pub extern const vexTaskStackUseGet: *const fn(_: u32) callconv(.c) types.int;
pub extern const vexTaskStateGetWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) u32;
pub extern const vexTaskStopWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) void;
pub extern const vexTaskSuspendWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) void;
pub extern const vexTaskWaitForExitWithId: *const fn(callback: [*c]void,ID: i32) callconv(.c) void;
pub extern const vexTaskYield: *const fn() callconv(.c) void;
